### ISSUE TITLE
Need to add a dependency for the `typhoeus` Gem to the `.gemspec`

### ISSUE THREAD

**Issue by h4w5** [baweaver/pokegem#2]
Error when first running:

```
$ pry
[1] pry(main)> require 'pokegem'
LoadError: cannot load such file -- typhoeus
from /home/pj/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by baweaver** [comment]
I'll fix that one when I get home tonight and push it.

**Comment by baweaver** [comment]
Scratch that, easy fix. v0.0.3 compensates for this and JSON missing: https://github.com/baweaver/pokegem/commit/faf360cddf99b91f22639d7f251de90e22a23a5c

**Comment by h4w5** [comment]
Awesome thanks!

On Tue, Feb 24, 2015 at 4:56 PM, Brandon Weaver <notifications@github.com>
wrote:

> Scratch that, easy fix. v0.0.3 compensates for this and JSON missing:
> faf360c
> <https://github.com/baweaver/pokegem/commit/faf360cddf99b91f22639d7f251de90e22a23a5c>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baweaver/pokegem/issues/2#issuecomment-75855131>.
>



-- 
Philip Hughes
H4W5
